interface StartupEntry {
  name: string;
  summary: string;
  industry: string;
  founderProfile: string;
  leadInvestor: string;
  fundingStage: string;
  fundingAmount: string;
  url: string;
  jobs: { title: string; url: string; source: string }[];
}

export function generateNewsletterHtml(
  startups: StartupEntry[],
  weekOf: string
): { subject: string; html: string } {
  const subject = `Startup Scanner: ${startups.length} AI Startups Hiring PMs — Week of ${weekOf}`;

  const startupCards = startups
    .map(
      (s) => `
    <div style="border:1px solid #e2e8f0;border-radius:8px;padding:20px;margin-bottom:16px;background:#fff;">
      <h2 style="margin:0 0 8px;color:#1a202c;font-size:18px;">
        <a href="${s.url}" style="color:#2563eb;text-decoration:none;">${s.name}</a>
      </h2>
      <div style="display:flex;gap:8px;margin-bottom:8px;flex-wrap:wrap;">
        <span style="background:#dbeafe;color:#1e40af;padding:2px 8px;border-radius:4px;font-size:12px;">${s.industry}</span>
        <span style="background:#dcfce7;color:#166534;padding:2px 8px;border-radius:4px;font-size:12px;">${s.fundingStage}${s.fundingAmount ? ` · ${s.fundingAmount}` : ""}</span>
      </div>
      <p style="color:#4a5568;font-size:14px;line-height:1.5;margin:0 0 12px;">${s.summary}</p>
      <p style="color:#718096;font-size:13px;margin:0 0 4px;"><strong>Founders:</strong> ${s.founderProfile}</p>
      <p style="color:#718096;font-size:13px;margin:0 0 12px;"><strong>Lead Investor:</strong> ${s.leadInvestor}</p>
      ${
        s.jobs.length > 0
          ? `<div style="border-top:1px solid #e2e8f0;padding-top:10px;margin-top:10px;">
              <p style="color:#1a202c;font-size:13px;font-weight:600;margin:0 0 6px;">Open Product Roles:</p>
              ${s.jobs
                .map(
                  (j) =>
                    `<a href="${j.url}" style="display:inline-block;background:#f0f9ff;color:#2563eb;padding:4px 10px;border-radius:4px;font-size:12px;text-decoration:none;margin:2px 4px 2px 0;">${j.title} (${j.source})</a>`
                )
                .join("")}
            </div>`
          : ""
      }
    </div>`
    )
    .join("");

  const html = `<!DOCTYPE html>
<html>
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width"></head>
<body style="font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;background:#f7fafc;padding:20px;margin:0;">
  <div style="max-width:600px;margin:0 auto;">
    <h1 style="color:#1a202c;font-size:24px;margin-bottom:4px;">Startup Scanner</h1>
    <p style="color:#718096;margin:0 0 24px;">Week of ${weekOf} · ${startups.length} AI startups raising seed/Series A and hiring for product roles</p>
    ${startupCards}
    <p style="color:#a0aec0;font-size:12px;text-align:center;margin-top:32px;">Generated by Startup Scanner</p>
  </div>
</body>
</html>`;

  return { subject, html };
}
